[video_source]
path = "/dev/video0"
format = "v4l2"
video_codec = "h264_v4l2m2m"
display_size = [960, 540]

[video_source.options]
# framerate = "10"
video_size = "1920x1080"
input_format = "h264"

[image]
layout = "two_by_two"
prefix = "pb_"
enable_post_command = false
post_command = ["lpr"]