[video_source]
path = "/dev/video0"
format = "v4l2"
video_codec = "h264_v4l2m2m"

[video_source.options]
# framerate = "10"
video_size = "1920x1080"
input_format = "h264"

[image]
prefix = "pb_"

[print]
enable = false
